# Generated by Django 5.0.1 on 2024-01-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=555, null=True)),
                ('first_name', models.CharField(blank=True, max_length=555, null=True)),
                ('last_name', models.CharField(blank=True, max_length=555, null=True)),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('uzbek', models.CharField(max_length=255)),
                ('a', models.CharField(blank=True, max_length=255, null=True)),
                ('b', models.CharField(blank=True, max_length=255, null=True)),
                ('c', models.CharField(blank=True, max_length=255, null=True)),
                ('d', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "So'z",
                'verbose_name_plural': "So'zlar",
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='images')),
                ('text', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.category')),
            ],
        ),
    ]
