# Generated by Django 5.0.1 on 2024-01-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='a',
            new_name='v1',
        ),
        migrations.RenameField(
            model_name='words',
            old_name='b',
            new_name='v2',
        ),
        migrations.RenameField(
            model_name='words',
            old_name='c',
            new_name='v3',
        ),
        migrations.RenameField(
            model_name='words',
            old_name='d',
            new_name='v4',
        ),
    ]
